@startuml
skinparam linetype polyline
hide circle
hide stereotype


skinparam class<<TM>> {
 BorderColor #505090
 BackgroundColor APPLICATION
 HeaderBackgroundColor SkyBlue
}


class "**MedicationLine**" as BELMMedicationLine <<TM>>{
  |_ uniqueIdentifier 1..1   
  |_ versionIdentifier 1..1   
  |_ basedOnMedicationLine 0..1
  |_ groupIdentifier 0..*   
  |_ patient 1..1   
  |_ status 1..1   
  |_ statusReason 0..1   
  |_ category 0..1   
    |_ originType 0..1   
  |_ medication 1..1   
    |_ product 1..1   
    |_ type 1..1   
  |_ requester 1..1   
  |_ indication 0..*   
    |_ reference 0..1   
    |_ code 0..1   
  |_ dispenseRequest 0..*   
    |_ dispenseInterval 0..1
    |_ quantityPerDispense 0..1
  |_ dosage 0..1   
    |_ dosageDetails 0..1   
    |_ dosageOverride 0..1   
    |_ dosageOverrideReason 1..1   
  |_ note 0..*   
'  |_ lastUpdatedDate 1..1   
'  |_ recordedDate 0..1   
'  |_ assertedDate 0..1   
'  |_ recorder 1..1   
'  |_ exposure 0..1   
'  |_ effectivePeriod 1..1   
'    |_ start 1..1   
'    |_ end 0..1   
'  |_ adherence 0..1   
'    |_ code 1..1   
'    |_ adherenceReason 0..1   
'  |_ visibility 0..*   
  --
'* basedOnMedicationLine 0..1 Reference (BEModelMedicationLine) "Link to the Medication Line from which this request is based"
'* patient 1..1 Reference "The person for whom the medication is prescribed/ordered" "Question: would we want to add basic Patient model?"
'* status 1..1 CD "Status of the prescription, this should not be status of treatment"
'* statusReason 0..* CD "Reason for the current status of prescription, for example the reason why the prescription was made invalid"
'* statusReasonText 0..1 ST "Textual reason for the current status of prescription"
'* medication 1..1 Reference (BeModelMedication) "Prescribed product, branded, generic, virtual, extemporaneous, etc"
'* prescriber 1..1 Reference (Practitioner or PractitionerRole) "The person who made the prescription, and who takes the responsibility of the treatment" "Question: would we want to add basic Practicioner model?"
'* indication 0..* Class "Reason for the prescription (typically diagnosis, or a procedure)"
'  * reference 0..* CD "Reason for the prescription (typically diagnosis, or a procedure)"
'  * code 0..* CD "Reason for the prescription (typically diagnosis, or a procedure)"
'  * text 0..1 ST "Reason for the prescription in textual form. This might not be allowed by some implementations."
'* dosage 1..1 DosagingInformation "Dosaging and administration instructions"
'* validFrom 0..1 DT "Effective date of the prescription. The prescription is not dispensable before this date. In most cases this information repeats issueDate"
'* validUntil 0..1 DT "The validity period end date. The prescription is not dispensable after this date."
'* category 0..* CD "Category or categories of prescription. For example type of reimbursement, or type of prescription (e.g. hospital, private, etc)."
'* note 0..* ST "Additional information or comments"
'* groupIdentifier 0..1 II "Identifier for the group that this prescription belongs to. This might be the common identifier in use cases where one national prescription contains several medication items, which can be handled as separate orders"
'* recordingDate 0..1 DT "Time of authoring the prescription/draft in the information system"
'* issueDate 1..1 DT "Time of issuing (signing) the prescription by health care practicioner"
'* recorder 0..1 Reference(Practitioner or PractitionerRole) "The recorder of the prescription/draft in the information system"
'//* usageInstructions 1..1 Reference(DosagingInformation) "Dosaging and administration instructions"
'//* preparationInstructions 0..* ST "Additional instructions about preparation or dispense" 
'* noSubstitution 0..1 BackboneElement "Substitution is not allowed for a given reason" 
'  * noSubstitutionFlag 1..1 BL "Substitution of the product is not allowed."
'  * noSubstitutionReason 0..1 CD "Coded reason for the no-substitution requirement"
'  * noSubstitutionReasonText 0..1 ST "Textual reason for the no-substitution requirement"
'* allowedSubstitutionType 0..* CD "Specific type of substitution that is allowed. Can be an explicit relaxation to normal jurisdictional substitution rules, especially in hospital context."
}
@enduml