@startuml
skinparam linetype polyline
hide circle
hide stereotype


skinparam class<<TM>> {
 BorderColor #505090
 BackgroundColor APPLICATION
 HeaderBackgroundColor SkyBlue
}


class "**MedicationLine**" as BELMMedicationLine <<TM>>{
  |_ uniqueIdentifier 1..1   
  |_ versionIdentifier 1..1   
  |_ lastUpdatedDate 1..1   
  |_ status 1..1   
  |_ statusReason 0..1   
  |_ recordedDate 0..1   
  |_ assertedDate 0..1   
  |_ recorder 1..1   
  |_ patient 1..1   
  |_ category 0..1   
    |_ originType 0..1   
  |_ medication 1..1   
    |_ product 1..1   
    |_ type 1..1   
  |_ exposure 0..1   
  |_ reason 0..*   
    |_ reference 0..1   
    |_ code 0..1   
  |_ effectivePeriod 1..1   
    |_ start 1..1   
    |_ end 0..1   
  |_ adherence 0..1   
    |_ code 1..1   
    |_ adherenceReason 0..1   
  |_ dosage 0..1   
    |_ dosageDetails 0..1   
    |_ dosageOverride 0..1   
    |_ dosageOverrideReason 1..1   
  |_ note 0..*   
  |_ dispenseRequestNeeded 0..*   
  |_ visibility 0..*   
}
@enduml