@startuml
!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0
!includeurl ICONURL/common.puml
!includeurl ICONURL/font-awesome-5/database.puml

'skinparam linetype ortho
'skinparam linetype polyline
hide circle
hide stereotype

'skinparam defaultFontName Avenir-Book
'skinparam defaultFontSize 17
'skinparam monochrome true


'!pragma layout smetana

skinparam class<<MD>> {
 BorderColor DarkSlateGray
 BackgroundColor WhiteSmoke
 HeaderBackgroundColor #909090
}

skinparam class<<TM>> {
 BorderColor #505090
 BackgroundColor APPLICATION
 HeaderBackgroundColor SkyBlue
}


skinparam class<<Doc>> {
 BorderColor #505090
 BackgroundColor APPLICATION
 HeaderBackgroundColor SkyBlue
}

<style>
file {
  BackGroundColor APPLICATION
  LineThickness 1
  LineColor black
}
</style>

'file MDd [
'  MedicationSchema
'  ===
'  |_ patient
'  |_ LastUpdate
'  |_ Label
'  |_ Version
'  ]


class "** Medication Schema **" as MS<<TM>> {
  --
  |_ patient
  |_ lastUpdate
  |_ label
  |_ version
}


class "** Medication Product **" as M<<TM>> {
  --
    |_ identifier 1..*
    |_ doseForm 0..1
    |_ name 0..1
    |_ ingredient 0..1
      |_ strength 0..1
      |_ product 0..1
    }

class "**Medication Line**" as ML<<TM>> {
  |_ uniqueIdentifier 1..*
  |_ lastRecordedDate 1..*
  |_ status
  |_ statusReason
  |_ recordedDate
  |_ assertedDate
  |_ recorder
  |_ exposure
  |_ patient 1..1
  |_ medication
    |_ product/substance
    |_ type
  |_ reason
    |_ reference 
    |_ code
  |_ effectivePeriod
    |_ start
    |_ end
  |_ dosage
    |_ dosageOverride
    |_ dosageOverrideReason
    |_ dosageDetails
      |_ text
      |_ timing
        |_ event
        |_ repeat
          |_ duration
          |_ period
          |_ dayOfWeek
            |_ when
              |_ BePeriod
      |_ route
      |_ doseQuantity
        |_ value
        |_ unit
      |_ patientInstruction
  |_ adherence
    |_ code
    |_ reason
  |_ note
  |_ <i>originType
  |_ dispenseRequestNeeded?   
  |_ visible
--
<i>Identifier NameSpace
}


' class "**Prescription (Group)**" as P<<TM>> {
'   |_ identifier 1..* 
'   |_ status?
'   |_ period?
'   |_ indication
'   |_ comment?
'   |_ coverage?
' }


'P -u-> ML : supportingInformation
class "**Prescription Line**" as PL<<TM>> {
  |_ identifier 1..* 
  |_ authoredOn
  |_ supportingInformation   
  |_ subject
  |_ status
  |_ statusReason
  |_ intent?
  |_ medication
  |_ requester
  |_ reason
  |_ dosage
  |_ effectivePeriod
    |_ start
    |_ end
  |_ dispenseRequest
    |_ quantity
    |_ dispenseInterval
    |_ validityPeriod
  |_ visible <&list>
--
<i>Substitution?
}


class "**Dispense**" as D<<TM>> {
  |_ identifier 1..*
  |_ patient 0..1 
  |_ receiver 0..1 
  |_ dispenser 0..1
    |_ dispenser 0..1
    |_ <i>organization 0..1
  |_ prescription 1..1
    |_ isPrescribed 1..1
    |_ request 1..1
  |_ <b>status 1..1 
  |_ statusReasonCoded 0..1 
  |_ statusReasonText 0..1 
  |_ dispenseDate  <b><u>1</u></b>..1
  |_ dispensedItem 0..1
    |_ medication 0..1 
    |_ dispensedQuantity 0..1
    |_ dosageInstructions 0..1
    |_ note 0..1
  |_ <b>substitution  0..1 
  |_ <b>coverage 0..1 
    |_ <b>reimbursementRate 0..1
}


'M <-u- ML : medication

ML -u-o MS : ""

PL -r-> M :" medication "



PL <.l.> ML : supportingInformation

D <.u.> ML : supportingInformation
ML -d-> M : "                   "

'M -u[hidden]-> MS



D -l-> PL :" authorizedBy "
D -l-> M :" medication "
'P o-r- PL :"           "
'PL -r[hidden]- M
'PL ||-d-o{ M :"                  "

@enduml
