@startuml
title Use Case 2 - Update Medication Schema
skinparam actorStyle awesome

hide footbox

'!include ./style.iuml

actor "**Patient**" as P
actor "**GP**" as GP
Participant "** Pharmacy **\n**  System  **" as PIS
Participant "** Vault / other **\n **  System  **" as V

group Identification
P -[#A92]-> PIS : Identification / authorization
end
...

group Request Medication Summary
PIS <- V : **Return Medication Summary**
end

...

group Request Medication Summary
GP --> PIS : Update Medication Summary
activate PIS
PIS -> V : Submit updated\nMedication Summary
deactivate PIS
activate V
V -> V : Update version\nMedication Summary
deactivate V
end

@enduml
