@startuml
title Use Case 2 - Update Medication Record \n (e.g. add a new medication line)
skinparam actorStyle awesome

hide footbox

'!include ./style.iuml

actor "**Patient**" as P
actor "**GP**" as GP
Participant " **Order Entry** \n ** System **" as PIS
Participant " **Vault / other** \n **  System  **" as V

group Identification
P -[#A92]-> PIS : Identification / authorization
end
...

group Request Medication Record
PIS <- V : Return Medication Record
end

...

group Request Medication Record
GP --> PIS : Create new medication line
activate PIS

PIS -> V : Send new Medication Line
deactivate PIS
activate V
V -> V : Update version\nMedication Line
deactivate V
end

@enduml
