@startuml
title Use Case 3  -  Compile Medication Schema \n
skinparam actorStyle awesome
!pragma teoz true
hide footbox

'!include ./style.iuml

'actor "**Patient**" as P
actor "**GP**" as GP
Participant " **Pharmacy**\n  **System**  " as PIS
Participant " **Vault / other **\n  **System** " as V
Participant " **Other **\n  **Sources**" as Src

...

group Collect Medication Information
PIS -> V : Submit Medication Lines\n(or other information)
activate PIS
activate V
Src -> V : Submit other\nMedication Lines \n(or other information)
deactivate PIS
V -> V : Aggregate\nMedication Lines\n(or other information)
deactivate V

end
...

group Compile Medication Summary
V -> V : Reconcile \nMedication Information
activate V
...
V -> V : Create / Update\nMedication Record
deactivate V
end

...

group Request Medication Summary
GP --> PIS : Request Patient's\nmedication record
activate PIS
PIS -> V : Query for Medication Record
activate V
PIS <- V : **Return Medication Record**
deactivate V
deactivate PIS
end


@enduml
